# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# To create the conda environment:
# $ conda env create -f environment.yml
#
# To update the conda environment:
# $ conda env update -f environment.yml
#
# To register the conda environment in Jupyter:
# $ conda activate forecasting_env
# $ python -m ipykernel install --user --name forecasting_env

name: forecasting_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6.10
  - pip>=19.0.3
  - jupyter>=1.0.0
  - ipykernel>=4.6.1
  - jupyter_nbextensions_configurator=0.4.1
  - scipy=1.1.0
  - numpy=1.16.2
  - pandas=0.23.4
  - scikit-learn=0.20.3
  - pytest>=3.6.4
  - pylint
  - papermill>=1.0.1
  - matplotlib=3.1.2
  - r-base>=3.3.0
  - pip:
    - black>=18.6b4
    - flake8>=3.3.0
    - jupytext>=1.3.0
    - lightgbm==2.3.0
    - tensorflow==2.0
    - tensorboard==2.1.0
    - nteract-scrapbook==0.3.1
    - statsmodels>=0.11.1
    - pmdarima==1.1.1
    - azureml-sdk[automl,notebooks]==1.0.85
